package com.afk.model.entity.enums;

public enum TipoServicio {
    PLOMERIA,ELECTRICIDAD,CARPINTERIA,PINTURA,REPARACION_ELECTRODOMESTICOS,
    ALBAÑILERIA,LIMPIEZA_GENERAL,INSTALACION_SISTEMAS_ALARMAS,INSTALACION_SISTEMA_CAMARAS,
    INSTALACION_CERRADURAS,RENOVACION_ACABADOS,JARDINERIA,MUDANZAS,INSTALACION_INTERNET,
    TRANSPORTE_MERCANCIA,
}
