package com.afk.model.entity.enums;

public enum TipoPago {
    TARJETA_CREDITO, TARJETA_DEBITO, APPLE_PAY,
    GOOGLE_PAY, TRANSFERENCIA_BANCARIA, SEPA_DIRECT_DEBIT, PAGO_LOCAL,
    ARRIENDO, DEPOSITO, SERVICIO, MANTENIMIENTO, OTRO
}
